spring:
  application:
    name: order-service

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/architecture_lab}
    username: ${SPRING_R2DBC_USERNAME:architecture_user}
    password: ${SPRING_R2DBC_PASSWORD:architecture_password}

    pool:
      enabled: true
      initial-size: 2
      max-size: 10

  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/architecture_lab}
    user: ${SPRING_FLYWAY_USER:architecture_user}
    password: ${SPRING_FLYWAY_PASSWORD:architecture_password}

logging:
  level:
    org.springframework.r2dbc: DEBUG
